version: '3.6'
services: 
  db:
    image: postgres
    restart: always
    environment:  
      DATABASE_HOST: ${DATABASE_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}

    ports: 
        - "5432:5432" 